### ISSUE TITLE
create DetailMapView

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/landslides-post-wildfire-debris-flow#11]
The details page will no longer have a leaflet map. The detailed view on the details page will be an image (png) that shows a static view of the segmented basin. This image will be referenced in the feed as `attributes.mapImage`. Work for this ticket will be incorporated into the DetailView.

To do:
 - Build reference to detailed map image (`attributes.map + ".png"`)
 - Display the detailed map

**Comment by jdbrown-USGS** [comment]
pull request #42 had these changes in it.
