### ISSUE TITLE
Update DetailsView to use images

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/landslides-post-wildfire-debris-flow#39]
When an event is more than two years old the leaflet map will be traded for a static image of the   "Segmented Probability" layer. 

The image will be used as soon as the event is two calendar years old. This means that as soon as we enter into 2017, that only 2017 and 2016 will use a leaflet map and all 2015 events will use the static image provided on the FTP server. 

The image and pdf to be displayed can be found on the ftp server, at:
 - ftp://hazards.cr.usgs.gov/web/landslides-post-wildfire-debris-flow/fires/<mapImage>/image.png
 - ftp://hazards.cr.usgs.gov/web/landslides-post-wildfire-debris-flow/fires/<mapImage>/image.pdf

**Comment by jmfee-usgs** [comment]
I'm a little concerned about the YYYYMMDD being part of the url: what if the fire date is changed after the fact?  maybe make this part of the `<mapImage>` variable?

**Comment by ehunter-usgs** [comment]
@jmfee-usgs I was confused by greg's naming convention, YYYYMMDD is part of the `mapImage` attribute
